name: pulse
version: "0.1.0"
config-version: 2
profile: pulse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  data_dir: '{{ env_var("PULSE_DATA_DIR", "../data") }}'

models:
  pulse:
    +materialized: table
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
